### ISSUE TITLE
"Fail to find serializer" error when using 1.1.0 on Android

### ISSUE THREAD

**Issue by dogriffiths** [TelemetryDeck/KotlinSDK#26]
I tried to use version 2.0.1, unfortunately that led to a bunch of version issues with class file formats and Kotlin versions on the app.

So I tried instead to use v 1.1.0. No signals were sent, and debugging through the code, an exception is being thrown in the send method of TelemetryManager, saying:

    Fail to find serializer. Consider to add one of the following dependencies: 
     - ktor-client-gson
     - ktor-client-json
     - ktor-client-serialization

I have tried adding additional dependencies for these libraries, but to no avail.

Are there additional libraries and/or setup code required to get the library to work?

**Comment by kkostov** [comment]
Hi @dogriffiths, thank you for reporting this. The older version 1.x indeed has a build issue with more recent releases of Kotlin and Ktor.

There have been several improvements to the library since then that should mitigate the build problem - could you test version `2.0.2`?


Regarding outgoing signals, I will need some more information regarding your setup. 

* Would it possible to set `showDebugLogs` to `true` either in the manifest or programatically using the builder and share all Logcat output from `D/TELEMETRYDECK`. Normally we log all information about queued signals and if there are any problems submitting them to the server. This will be very helpful to troubleshoot if something is going wrong.

If the problem still persists, here are some additional bits of information that can be of help to track it down:
* That's probably a yes, but just to be sure - Does your app declare permission to access the internet? (`<uses-permission android:name="android.permission.INTERNET" />`.
* Could you share a snippet of how you start the TelemetryManager - programatically or via the manifest?


Thank you!
